import Head from "next/head";
import Image from "next/image";
import styles from "../public/scss/Home.module.css";
import Nav from "./components/Nav";

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Hidahis Mesa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <Nav />
        <section className={`${styles.splash} bg-neutral-200`}>
          <Image
            src="/Mesa_Hidahis.jpg"
            width={600}
            height={613}
            layout="responsive"
            alt="A picture of me"
            className={styles.splash__img}
          />
        </section>
        <section className={`${styles.splash__content} bg-neutral-200`}>
          <h1
            className={`${styles.splash__small__title} text-neutral-900 fw-regular fs-smallest-heading`}
          >
            Hello, my name is
          </h1>
          <h1
            className={`${styles.splash__title} text-neutral-900 fw-bold fs-primary-heading`}
          >
            Hidahis Mesa
          </h1>
          <p className={`${styles.splash__about} text-neutral-700`}>
            I am doctorate student in policy and leadership studies at
            Vanderbilt University.
          </p>
          <button
            className={`${styles.primary__button} fs-button bg-accent-400 text-neutral-100`}
          >
            Contact Me
          </button>
        </section>
        <main>
          <section className={`${styles.about}`} id="aboutme">
            <h2
              className={`${styles.content__title} fw-bold fs-secondary-heading`}
            >
              About Me
            </h2>
            <div className={`${styles.content__divider} bg-neutral-700`} />
            <p>
              I am a Ph.D. student in the Department of Leadership, Policy, and
              Organizations at Vanderbilt University’s Peabody College. My
              research focuses on college access for underrepresented students,
              community college student success, and pipelines into regional
              comprehensive universities. Currently, I work with Dr. Adela Soliz
              and with the Tennessee Post-secondary Evaluation and Analysis
              Research Lab (TN-PEARL).
            </p>
            <p>
              Prior to entering the Ph.D. program, I worked at San Diego State
              University as an institutional research analyst. I received a
              bachelor's degree in Political Science from the University of
              Florida and a master's degree in Urban
            </p>
          </section>
          <section className={`${styles.about}`} id="presentations">
            <h2
              className={`${styles.content__title} fw-bold fs-secondary-heading`}
            >
              About Me
            </h2>
            <div className={`${styles.content__divider} bg-neutral-700`} />
            <p>
              I am a Ph.D. student in the Department of Leadership, Policy, and
              Organizations at Vanderbilt University’s Peabody College. My
              research focuses on college access for underrepresented students,
              community college student success, and pipelines into regional
              comprehensive universities. Currently, I work with Dr. Adela Soliz
              and with the Tennessee Post-secondary Evaluation and Analysis
              Research Lab (TN-PEARL).
            </p>
            <p>
              Prior to entering the Ph.D. program, I worked at San Diego State
              University as an institutional research analyst. I received a
              bachelor's degree in Political Science from the University of
              Florida and a master's degree in Urban
            </p>
          </section>
        </main>
        <footer>dfsdfds</footer>
      </div>

  );
}
