import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "./scss/Home.module.css";
import Button from "./components/Button";
import ContactForm from "./components/ContactForm";
import Nav from "./components/Nav";

export default function Home() {
  const contactRef = useRef(null);

  const scrollHandler = () => contactRef.current.scrollIntoView();

  return (
    <div className={styles.container}>
      <Head>
        <title>Hidahis Mesa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <section className="bg-neutral-200">
        <section
          id="splash"
          className={`${styles.splash__content} bg-neutral-200`}
        >
          <section className={`${styles.splash} bg-neutral-200`}>
            <Image
              src="/Mesa_Hidahis.jpg"
              width={600}
              height={613}
              alt="A picture of me"
              className={styles.splash__img}
            />
          </section>
          <section className={styles.splash}>
            <h1
              className={`${styles.splash__small__title} text-neutral-900 fw-regular fs-smallest-heading`}
            >
              Hello, my name is
            </h1>
            <h1
              className={`${styles.splash__title} text-neutral-900 fw-bold fs-primary-heading`}
            >
              Hidahis Mesa
            </h1>
            <p className={`${styles.splash__about} text-neutral-700`}>
              I am doctorate student in policy and leadership studies at
              Vanderbilt University.
            </p>
            <Button
              primary={true}
              style="bg-accent-400"
              scrollHandler={scrollHandler}
            >
              Contact Me
            </Button>
          </section>
        </section>
      </section>
      <main>
        <section className={`${styles.section} text-neutral-700`} id="aboutme">
          <h2
            className={`${styles.content__title} text-neutral-900 fw-bold fs-secondary-heading`}
          >
            About Me
          </h2>
          <div className={`${styles.content__divider} bg-neutral-700 `} />
          <p>
            I am a Ph.D. student in the Department of Leadership, Policy, and
            Organizations at Vanderbilt University&apos;s Peabody College. My
            research focuses on college access for underrepresented students,
            community college student success, and pipelines into regional
            comprehensive universities. Currently, I work with Dr. Adela Soliz
            and with the Tennessee Post-secondary Evaluation and Analysis
            Research Lab (TN-PEARL).
          </p>
          <p>
            Prior to entering the Ph.D. program, I worked at San Diego State
            University as an institutional research analyst. I received a
            bachelor&apos;s degree in Political Science from the University of
            Florida and a master&apos;s degree in Urban Education Policy from
            Brown University.
          </p>
        </section>
        <section
          className={`${styles.section} text-neutral-700`}
          id="presentations"
        >
          <h2
            className={`${styles.content__title} text-neutral-900 fw-bold fs-secondary-heading`}
          >
            Presentations
          </h2>
          <div className={`${styles.content__divider} bg-neutral-700`} />
          <p>
            Soliz, A., & Mesa, H. (2022, March). Successfully Navigating
            Transfer: How Students Leverage Resources and Overcome Challenges to
            Achieve Transfer Goals. In 2021 APPAM Fall Research Conference.
            APPAM.
          </p>
          <p>
            Soliz, A., & Mesa, H. (2020, November). What Is the Effect of
            Institution-Level Articulation Policies on Vertical Transfer Rates
            for Community College Students?. In 2020 APPAM Fall Research
            Conference. APPAM.
          </p>
          <p>
            Soliz, A., DeLoach, C. A., & Mesa, H. (2022, March). Building
            Collaborations to Improve Workforce Development. In 2021 APPAM Fall
            Research Conference. APPAM.
          </p>
          <p>
            Soliz, A., & Mesa, H. (2022, March). Successfully Navigating
            Transfer: How Students Leverage Resources and Overcome Challenges to
            Achieve Transfer Goals. In 2021 APPAM Fall Research Conference.
            APPAM.
          </p>
        </section>
        <section className={`${styles.section} text-neutral-700`} id="contact">
          <ContactForm
            contactRef={contactRef}
            styles={styles["content__title"]}
          />
        </section>
      </main>
      <footer>
        <h6>Copyright © 2022 Celia Saumell</h6>
      </footer>
    </div>
  );
}
